server {
  listen 80;
  server_name _;

  location ^~ /api/ {
    proxy_pass http://backend:8080;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    add_header X-Routed-By "cgi-nginx-api" always;
  }

  location / {
    proxy_pass http://frontend:80;
    add_header X-Routed-By "cgi-nginx-frontend" always;
  }
}